package com.xiao.stock.demo.mapper;

import com.xiao.stock.demo.entity.OrderDemo;
import org.apache.ibatis.annotations.Param;

/**
 * Created by Mybatis Generator on 2019/10/19
 */
public interface OrderDemoMapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_demo
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_demo
     */
    int insert(OrderDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_demo
     */
    int insertSelective(OrderDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_demo
     */
    OrderDemo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_demo
     */
    int updateByPrimaryKeySelective(OrderDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_demo
     */
    int updateByPrimaryKey(OrderDemo record);

    // 获取订单信息
    OrderDemo getOrderByNo(String orderNo);

    // 取消订单
    int updateByOrderNo(@Param("orderNo") String orderNo, @Param("status") int status);
}