package com.xiao.stock.demo.mapper;

import com.xiao.stock.demo.entity.StockChangeLodDemo;
import org.apache.ibatis.annotations.Param;

/**
 * Created by Mybatis Generator on 2019/10/17
 */
public interface StockChangeLodDemoMapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change_log_demo
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change_log_demo
     */
    int insert(StockChangeLodDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change_log_demo
     */
    int insertSelective(StockChangeLodDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change_log_demo
     */
    StockChangeLodDemo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change_log_demo
     */
    int updateByPrimaryKeySelective(StockChangeLodDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change_log_demo
     */
    int updateByPrimaryKey(StockChangeLodDemo record);

    /**
     * 订单、商品、操作类型查询库存记录
     *
     * @param orderNo
     * @param productNo
     * @param optType
     * @return
     */
    StockChangeLodDemo selectByOrderNo(@Param("orderNo") String orderNo, @Param("productNo") String productNo,
            @Param("optType") String optType);
}