package com.xiao.stock.demo.entity;

import lombok.*;

import java.util.Date;

/**
 * t_order_demo
 * Created by Mybatis Generator on 2019/10/19
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class OrderDemo
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_demo.id
     *
     * @mbggenerated Sat Oct 19 09:17:42 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_demo.order_no
     *
     * @mbggenerated Sat Oct 19 09:17:42 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_demo.shop_code
     *
     * @mbggenerated Sat Oct 19 09:17:42 CST 2019
     */
    private String shopCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_demo.product_no
     *
     * @mbggenerated Sat Oct 19 09:17:42 CST 2019
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_demo.product_num
     *
     * @mbggenerated Sat Oct 19 09:17:42 CST 2019
     */
    private Integer productNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_demo.update_time
     *
     * @mbggenerated Sat Oct 19 09:17:42 CST 2019
     */
    private Date updateTime;

    private Integer status;
}