package com.xiao.stock.demo.entity;

import lombok.*;

import java.util.Date;

/**
 * t_stock_demo
 * Created by Mybatis Generator on 2019/10/17
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class StockDemo
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_demo.id
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_demo.product_no
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_demo.shop_code
     */
    private String shopCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_demo.pre_stock
     */
    private Integer preStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_demo.ava_stock
     */
    private Integer avaStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_demo.total_stock
     */
    private Integer totalStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_demo.update_time
     */
    private Date updateTime;

    /**
     * 订单号
     */
    private String orderNo;

    /**
     * 商品数量
     */
    private int productNum;

    /**
     * 更新预占库存
     */
    private Integer newPreStock;
    /**
     * 更新可用库存
     */
    private Integer newAvaStock;
    /**
     * 更新总库存
     */
    private Integer newTotalStock;
}