package com.xiao.stock.demo.entity;

import lombok.*;

import java.util.Date;

/**
 * t_stock_change_log_demo
 * Created by Mybatis Generator on 2019/10/17
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class StockChangeLodDemo
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.id
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.product_no
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.shop_code
     */
    private String shopCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.order_no
     */
    private String orderNo;

    /**
     * 操作类型
     */
    private String optType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.pre_stock_after
     */
    private Integer preStockAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.ava_stock_after
     */
    private Integer avaStockAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.total_stock_after
     */
    private Integer totalStockAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.pre_stock_before
     */
    private Integer preStockBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.ava_stock_before
     */
    private Integer avaStockBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.total_stock_before
     */
    private Integer totalStockBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change_log_demo.update_time
     */
    private Date updateTime;
}